# File: apps/pkm-indexer/nixpacks.toml
[phases.setup]
aptPkgs = [
  "python3-dev",
  "python3-pip",
  "build-essential",
  "tesseract-ocr"
]

[phases.build]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"